### ISSUE TITLE
Use Block RAM (BRAM) for memory

### ISSUE THREAD

**Issue by cbebe** [UofA-ECE-492-Project/riscv#5]
Doing DMA on the DDR stuff is too complicated! Maybe some other time if the 270KB BRAM is not enough for our applications.

To put into perspective, the Arduino mer

### Tasks

- [ ] Read tutorial on how to use BRAM
- [ ] Adjust the `mem` and `mem_sx` entities to match actual BRAM interface
- [ ] Connect BRAM on the constraints file
